### ISSUE TITLE
Auto-link doesn't work for titles ending in italics

### ISSUE THREAD

**Issue by TheBestPessimist** [naokazuterada/MarkdownTOC#136]
# How can the issue be reproduced
Have this title: `# I have some text: in _italics_`

# What was expected
Can click the TOC entry and jump to my specific heading. (scroll location changes)

# What actually occurred
The URL in the address bar changed, however I wasn't moved to my heading. (scroll location didn't chage)

# What was the version of the involved component
v3.0.3 installed from package control.

If i use `autoanchor="true"` then everything works correctly, just w/o it i have the problem.

Possibly related: https://github.com/naokazuterada/MarkdownTOC/issues/109#issuecomment-354932113

Please see this and rename to `a.md` [a.txt](https://github.com/naokazuterada/MarkdownTOC/files/3033676/a.txt)

**Comment by naokazuterada** [comment]
@TheBestPessimist Thank you for reporting. I will look into this weekend! : )

**Comment by naokazuterada** [comment]
@TheBestPessimist 

Hi, your problem will be fixed in 3.0.4.

https://github.com/naokazuterada/MarkdownTOC/releases/tag/3.0.4

You also check it [here](https://github.com/naokazuterada/MarkdownTOC-Tests/blob/eab057205f87be96701e903bb0bd9445e13a4450/example-for-136.md). This doc wrote with my sublime.

I close this issue, but it's OK if you still have the problem after plugin auto updated.
Thanks.

**Comment by TheBestPessimist** [comment]
I can confirm it works :)
