### ISSUE TITLE
Partial TOC generated for multiple mismatched blockquotes 

### ISSUE THREAD

**Issue by nrichards** [naokazuterada/MarkdownTOC#32]
Thank you for the very useful plugin!

_ISSUE_

Given certain markup having two headers we generate a TOC with one header.

Expected the TOC to contain _two_ headers.

_EXAMPLE_

<pre>
# Heading 1
 ```
 Blockquote 1 - notice the leading space ( ) for opening blockquote, and no-space for closing
```

# Heading 2 will be missing
 ```
 Blockquote 2 - notice again the same leading spacing as above
```
</pre>

_RESULT_

<pre>
&lt;!-- MarkdownTOC depth=3 bracket=round autolink=true -->

- [Heading 1](#heading-1)

&lt;!-- /MarkdownTOC -->
</pre>

**Comment by jonasbn** [comment]
I have looked at [the documentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/) from Github and it seems the reason why it works is the indentation inside the block. Since the code fence is not mandatory and basic indentation will render blocks as code. 

The documentation does not specify it explicitly, but indenting the code fence must be considered a typo.

@naokazuterada I recommend that this issue closed.

**Comment by naokazuterada** [comment]
@jonasbn Thank you for researching.

Now I could understand why @nrichards needs to insert spaces before ``` by reading your comment. It's indentation for codeblock itself, isn't it?

I fix this problem with commit above.
