### ISSUE TITLE
Use external TOC generator

### ISSUE THREAD

**Issue by dreamcat4** [naokazuterada/MarkdownTOC#37]
[EDIT] different TOC tool. Other one was not suitable.

The way this tool hooks into Sublime is very neat. Unfortunately, the same cannot be said for the TOC generation itself.

It would be easier to just replace the inside TOC generation to be calling this other tool:

https://github.com/thlorenz/doctoc

That one is already implemented and work very well to generate markdown TOC.
Mant thanks.

**Comment by naokazuterada** [comment]
@dreamcat4 ( @jonasbn )

So sorry for log time no response...

I think using external TOC generator is nice. But my concern is possibility of maintain existing features.

`doctoc` is not suitable for sublime text environment because it's node implementation.
I found python TOC generator instead.

https://github.com/rasbt/markdown-toclify

I haven't checked it.
In the future, I will think about including external toc generator into MarkdowTOC.

**Comment by jonasbn** [comment]
@naokazuterada as you state in your response an alternative TOC generator is nice, but possibly  beyond the scope and framework of this plugin. And main focus is integration with SublimeText. My recommendation is for this issue to be closed. If we are to consider possible extensions in this regard a PR with a proof of concept would be preferred.

**Comment by naokazuterada** [comment]
@jonasbn I agree with you. Thank you. I close this.
