### ISSUE TITLE
HTML tokens in headers should be ignored

### ISSUE THREAD

**Issue by lahmatiy** [naokazuterada/MarkdownTOC#73]
In headers (in markdown in general) HTML tokens can be used to escape special symbols. In this case tokens are converting to symbols and stripping from anchor. But currently letters and digits from token inserting into anchor.

Current (actual):

```md
<!-- MarkdownTOC -->

- [&lt;element>](#ltelement)  <!-- wrongly `lt` is added -->
- [&#60;element>](#60element)  <!-- wrongly `60` is added -->

<!-- /MarkdownTOC -->

## &lt;element>
## &#60;element>
```

Expected:

```md
<!-- MarkdownTOC -->

- [&lt;element>](#element)
- [&#60;element>](#element)

<!-- /MarkdownTOC -->

## &lt;element>
## &#60;element>
```

**Comment by naokazuterada** [comment]
You can set **strings** in `id_replacement` in version [2.1.1](https://github.com/naokazuterada/MarkdownTOC/releases/tag/2.1.1).

So, now you can get result you expected with new `id_replacement` setting like this.
```
"id_replacements": {
  "" : ["&lt;","&#60;","!","#","$","&","'","(",")","*","+",",","/",":",";","=","?","@","[","]","`","\"", ".","<",">","{","}","™","®","©"]
}
```
Only you have to do is update your plugin, because above setting is included new defaults. Please try it.

**Comment by lahmatiy** [comment]
@naokazuterada Yes, it's ok now. Thank you!
